const fs = require("fs");
const assert = require("assert");

const html = fs.readFileSync("index.html", "utf8");
const js = fs.readFileSync("app.js", "utf8");
const css = fs.readFileSync("styles.css", "utf8");

assert(html.includes('id="dateInput"'), "date picker should exist");
assert(html.includes('id="cartDrawer"'), "cart drawer should exist");
assert(html.includes('id="checkoutForm"'), "checkout form should exist");
assert(js.includes("localStorage.setItem(\"hl-invoices\""), "orders should be saved as invoices");
assert(js.includes("dateInput.min"), "minimum order date should be enforced");
assert(js.includes("dateInput.max"), "maximum order date should be enforced");
assert(js.includes("Math.max(6, Math.min(30"), "portion limits should be enforced");
assert(html.includes('id="heroImageAlt"'), "hero background image should have a text alternative");
assert(html.includes('aria-describedby="heroImageAlt"'), "hero should reference the background image text alternative");
assert(js.includes("function foodImageAlt"), "menu images should use intentional alt text");
assert(js.includes('alt="${foodImageAlt(food)}"'), "food images should render descriptive alt attributes");
assert(js.includes('<img src="${entry.image}" alt="">'), "cart thumbnails should be ignored by assistive technology");
assert(html.includes('role="group" aria-label="Menu category filters"'), "filter controls should expose their group relationship");
assert(html.includes('aria-pressed="true"'), "active filter should expose selected state");
assert(html.includes('<dl class="about-stats"'), "business stats should use description list semantics");
assert(js.includes('<dl class="food-meta">'), "food card metadata should use description list semantics");
assert(js.includes('<ul class="ingredient-list">'), "ingredients should be exposed as a list");
assert(js.includes('<dl class="cart-item-meta">'), "cart item metadata should use description list semantics");
assert(js.includes("<dt>Subtotal</dt>"), "cart summary labels and values should be associated");
assert(js.includes('chip.setAttribute("aria-pressed", String(isActive))'), "filter state should update programmatically");
assert(css.includes("grid-template-columns: repeat(auto-fit, minmax(min(100%, 13rem), 1fr))"), "menu cards should reflow without horizontal scrolling");
assert(css.includes("@media (max-width: 720px)"), "narrow viewport layout rules should exist");
assert(css.includes("overflow-wrap: anywhere"), "long text should wrap in narrow viewports");
assert(css.includes(".table-wrap"), "wide tables should be contained in scrollable wrappers");
assert(css.includes("overflow-x: auto"), "table scrolling should be isolated to table containers");
assert(js.includes('aria-label="Scrollable nutrition facts table"'), "nutrition table wrapper should be named");
assert(js.includes('aria-label="Scrollable invoice items table"'), "invoice table wrapper should be named");
assert(html.includes('aria-label="Open navigation menu"'), "navigation toggle should expose a clear name");
assert(js.includes('aria-label", isOpen ? "Close navigation menu" : "Open navigation menu"'), "navigation toggle name should update with state");
assert(html.includes('data-open-cart aria-expanded="false" aria-controls="cartDrawer"'), "cart open controls should expose controlled state");
assert(html.includes('role="dialog" aria-modal="true" aria-labelledby="cartTitle"'), "cart dialog should expose name, role, and modal state");
assert(html.includes('role="dialog" aria-modal="true" aria-labelledby="invoiceTitle"'), "invoice dialog should expose name, role, and modal state");
assert(js.includes('aria-label="View details for ${food.name}"'), "generated details buttons should have unique accessible names");
assert(js.includes('aria-label="Add ${food.name} to cart"'), "generated add buttons should have unique accessible names");
assert(js.includes('aria-label="Remove ${entry.name} from cart"'), "generated remove buttons should have unique accessible names");
assert(js.includes('button.setAttribute("aria-expanded", "true")'), "cart open controls should update expanded state when opened");
assert(js.includes('button.setAttribute("aria-expanded", "false")'), "cart open controls should update expanded state when closed");
assert((js.match(/protein/g) || []).length >= 5, "protein category should be present");
assert((js.match(/vegetarian/g) || []).length >= 3, "vegetarian category should be present");
assert((js.match(/sides/g) || []).length >= 2, "sides category should be present");

console.log("Prototype checks passed.");
